#!/bin/bash

docker-compose -f or_cockroach/docker-compose.yml stop
docker-compose -f or_consent/docker-compose.yml stop
docker-compose -f or_hydra/docker-compose.yml stop
docker-compose -f or_keto/docker-compose.yml stop
docker-compose -f or_kratos/docker-compose.yml stop
docker-compose -f or_oathkeep/docker-compose.yml stop
docker-compose -f or_selfserv/docker-compose.yml stop
docker-compose -f or_traefik/docker-compose.yml stop

docker-compose -f or_cockroach/docker-compose.yml down
docker-compose -f or_consent/docker-compose.yml down
docker-compose -f or_hydra/docker-compose.yml down
docker-compose -f or_keto/docker-compose.yml down
docker-compose -f or_kratos/docker-compose.yml down
docker-compose -f or_oathkeep/docker-compose.yml down
docker-compose -f or_selfserv/docker-compose.yml down
docker-compose -f or_traefik/docker-compose.yml down

